### ISSUE TITLE
Type of squeezenet_v1.0.caffemodel is PCX image (image/x-pcx)?

### ISSUE THREAD

**Issue by saustar** [DeepScale/SqueezeNet#5]
Hi,
I have downloaded the provided model. But when I looked its properties, type is PCX image not binary??

How can I have a binary type??

**Comment by forresti** [comment]
Interesting. I assume you are talking about the *.caffemodel file?

Is Caffe able to load the file? 

In general, an OS tries to make an educated guess about file types, but this guess isn't always helpful.

**Comment by saustar** [comment]
Yes Caffe is able to load the model. But I am trying to convert it into
mxnet model. mxnet is not able to parse it. But its able to parse other
Caffe model . Only difference i can see is file type.

**Comment by forresti** [comment]
Since you say that you are able to load the pretrained SqueezeNet into Caffe, I'm going to close this issue.

I think an MXNet implementation of SqueezeNet is a great idea. I don't have any experience with MXNet, so I'm afraid I don't have any debugging advice. Instead of using our pretrained weights, perhaps you could train SqueezeNet from scratch in Caffe or MXNet? We just committed an update to the solver.prototxt file which makes SqueezeNet training converge more reliable.
