### ISSUE TITLE
Image normalization values

### ISSUE THREAD

**Issue by AlexMuresan** [DeepScale/SqueezeNet#62]
Is there any chance you could disclose the way in which the training dataset was normalized?

Thank you!

**Comment by forresti** [comment]
Good question. It's been a while since we did this work, but here is what I remember of how we prepared the training data:
- Warp each image to 256x256
- During training, crop a random 227x227 patch in each 256x256 image (different patch in each epoch), and feed the crop into the network. I believe we also did data augmentation by flipping the image in the horizontal dimension with a probability of 0.5.
- During inference, crop the center 224x224 pixels.
- Note that SqueezeNet has average pooling at the end, so you could actually feed in almost any image size if you want.
- As for normalization, I believe we calculated the average R, G, and B values, and we subtracted that value from the input data. Some people do a normalization grid (so R,0,0 would have a different value than R,0,1 in the normalization grid), but we just computed 3 scalar normalization values.
- I don't think we did any other data augmentation or normalization techniques. The field has come a long way in the last 4 years, and I think modern techniques for almost every aspect of training and inference would be superior to the approach we took in SqueezeNet. 

Good luck! I am going to close this issue, but you can still reply here if you have more questions.
